### ISSUE TITLE
Embed song isn't working

### ISSUE THREAD

**Issue by JudahGabriel** [JudahGabriel/Chavah#27]
Users can embed songs in their own blogs and HTML pages,

![image](https://user-images.githubusercontent.com/312936/33577841-ff61e75e-d909-11e7-9c3a-5e474e95f203.png)

Embed song used to work before porting to Angular. There are places around the web that have Chavah songs embedded (e.g. [14 Messianic wedding songs](http://blog.judahgabriel.com/2013/01/the-blessed-14-messianic-wedding-songs.html)), but those embeds are now displaying an HTML frame for Chavah that never plays the song.

Fix this so that those embed URLs work correctly. Also, make the embed option more visible; one user just asked if it was possible to embed, even though that functionality's been there for awhile.

**Comment by kdcllc** [comment]
Example url: http://messianicradio.com/home/embed?song=songs/2982/
