### ISSUE TITLE
Make Chavah a PWA

### ISSUE THREAD

**Issue by JudahGabriel** [JudahGabriel/Chavah#29]
Chavah functions as a web _app_. Since it's an app, we'd like to be able to add Chavah to mobile home screen, support push notifications, perhaps have basic offline support, and even be listed in app stores.

The [Progressive Web Apps (PWA)](https://developers.google.com/web/progressive-web-apps/) standards promise to make web apps first-class citizens on host operating systems: akin to a native app on mobile and desktop. It enables offline support, "add to homescreen/desktop", service workers, push notifications, and [future app store support](https://blogs.windows.com/msedgedev/2016/07/08/the-progress-of-web-apps/).

We've tested out [Mads Kristensen's .NET Core PWA nuget package](https://github.com/madskristensen/WebEssentials.AspNetCore.ServiceWorker). It *almost* works. The problem is, it [adds everything to the browser cache](https://github.com/madskristensen/WebEssentials.AspNetCore.ServiceWorker/issues/10). This is problematic because it will add even MP3s to the cache, which will eventually overflow the cache quota.

Two paths we could take: 

1. Submit a PR to the .NET Core PWA package to support caching only certain resources, [as suggested here](https://github.com/madskristensen/WebEssentials.AspNetCore.ServiceWorker/issues/10).
2. Custom code our own service worker and all the supporting bits to just cache the things we want.

I'm currently leaning towards the first option.

**Comment by JudahGabriel** [comment]
I see Google announced they are deprecating Chrome apps in favor of PWAs, and that [Chrome will allow you to install PWAs onto the desktop in 2018](https://www.youtube.com/watch?v=_sLa0qhuqcA&feature=youtu.be&t=32m29s). I like this direction; it reconfirms that PWAs will be a larger, standardized platform in the future.

More good news: I [submitted a PR](https://github.com/madskristensen/WebEssentials.AspNetCore.ServiceWorker/pull/12) to Mads Kristensen's .NET Core PWA package that allows it to work well for Chavah. It was accepted yesterday, I'm glad to say, so Chavah will utilize this very soon and be a full-fledged PWA.

**Comment by JudahGabriel** [comment]
Completed. We're now running Chavah as a PWA with a service worker. The service worker is configured to cache all fingerprinted resources (resources with a ?v= query string). 

I updated Chavah so that the whole shell is cached. This includes the HTML files, JS, CSS, web fonts, and 3rd party CDN resources. This gives us a nice speed boost on successive reloads: all resources are served from the cache, and it takes a mere 43ms to load the whole Chavah shell.

We're not caching MP3s or album art, so while Chavah can run offline, there won't be any music. We may want to think about implementing some small offline cache of some music and album art in the future.

We may also want to trigger the PWA installation prompt after some time. We'll file those as separate issues later.

**Comment by kdcllc** [comment]
@JudahGabriel, so I was thinking we can allow users to specify what kind of music can be cached via PWA thru their profile settings. We can't cache much but some kind of setting should allow for this kind of customization. Thoughts?

**Comment by JudahGabriel** [comment]
Basically a way to make some songs available offline. Yeah, I'm up for that. Perhaps it's something we could add to the profile as we flesh that out.
