### ISSUE TITLE
Fill out the profile page

### ISSUE THREAD

**Issue by JudahGabriel** [JudahGabriel/Chavah#33]
A user's profile page should allow them to add their first name, last name, profile pic. 

They should be able to see their favorite artists, albums, songs, and tags. They should be able to see the song edits they've submitted. They should be able to see the song requests they've made.

**Comment by kdcllc** [comment]
The following fields to be added:
- First Name 
- Last Name
- Profile picture - What do you have in mind for image storage? Where will the image be stored?
-  List of Artists
- List of Albums?
- List of Songs
- List of tags
- List of the song edits and the ability to navigate to update if needed?
- List of song requests

**Comment by JudahGabriel** [comment]
Image storage: I'm thinking we leverage our existing FTP/CDN stuff. Right now we have a folder for audio, another for album art. We add another for profile pics.

List of X: I'm thinking these don't need to be part of the user profile, but rather populated dynamically. (Probably leveraging our existing UserSongPreferences class. But I suggest we tackle the list of X later. Let's add first and last name and profile picture. Get that working with UI, then we can build more from there.

**Comment by JudahGabriel** [comment]
I've implemented editing for first name, last name, and profile picture. I've also added some readonly user stats (registered, total song play count, total song request count, others.)

In the future, we may add additional content here, but we'll add separate issues for htose.
