### ISSUE TITLE
Menu should show navigation

### ISSUE THREAD

**Issue by JudahGabriel** [JudahGabriel/Chavah#41]
On mobile, there's no way to access Trending, My Likes, Recent, Popular.

We should show these nav options in the menu. (Not just for mobile, but makes sense on all platforms.)

**Comment by kdcllc** [comment]
I agree with this. It is not really clear these options exist unless you listened for a while.

**Comment by JudahGabriel** [comment]
I've added menu nav for our completed pages (my likes, trending). We'll add nav for recent and popular when those pages are implemented.
