### ISSUE TITLE
Adding Home to the navigation

### ISSUE THREAD

**Issue by kdcllc** [JudahGabriel/Chavah#5]
@JudahGabriel I got the latest code and I think to improve the navigation for signed-in users it is beneficial to add "home" menu.

**Comment by JudahGabriel** [comment]
Agreed, this is a good idea. Often times in different UI screens, I'm adding a link to "back to the music" or something like that. It's insufficient. 

Also, clicking the big "Chavah Messianic Radio" title brings you home, but it's not very discoverable.

Having a home nav would be helpful. +1.
