### ISSUE TITLE
Update Chavah to .NET Core 2.1

### ISSUE THREAD

**Issue by JudahGabriel** [JudahGabriel/Chavah#61]
The new .NET Core features better performance along with nifty features like background task via the new [IHostedService](https://www.hanselman.com/blog/ASPNETCoreArchitectDavidFowlersHiddenGemsIn21.aspx).

This will also enable us to utilize [Raven.Migrations](https://github.com/migrating-ravens/RavenMigrations) and the new Raven.StructuredLog.

**Comment by kdcllc** [comment]
@JudahGabriel I have been working on that and also Docker support. [https://github.com/kdcllc/Chavah/tree/docker-dotnetsdk2.1]{https://github.com/kdcllc/Chavah/tree/docker-dotnetsdk2.1)

**Comment by JudahGabriel** [comment]
This will also enable us to utilize [Raven.Migrations](url) and the new Raven.StructuredLog.

**Comment by JudahGabriel** [comment]
That sounds great. Let me know if you need anything from me to make that happen.

**Comment by kdcllc** [comment]
@JudahGabriel I need help with seeding data for RavenDB :)

**Comment by JudahGabriel** [comment]
Ah. I've attached basic, simple seed data export for Raven.

You can import it via the Studio (Settings -> Import Data) or via code ([docStore.Smuggler.ImportAsync(...)](https://ravendb.net/docs/article-page/4.0/csharp/client-api/smuggler/what-is-smuggler). 

Is that what you're looking for?

[RavenSeedData.zip](https://github.com/JudahGabriel/Chavah/files/2242748/RavenSeedData.zip)

**Comment by kdcllc** [comment]
@JudahGabriel so I tried that and It seems that it creates database structure. What are my options for seeding db as well? Do I need to extract json file somehow?

**Comment by JudahGabriel** [comment]
@kdcllc I saw your email about some uncertainty about this seed data. Did you figure it out? 

Your steps here would be:

1. Unzip RavenSeedData.zip - it contains a single .ravendump file
2. Import the .ravendump file, either via the Studio (Settings -> Import Data) or code (docStore.Smuggler.ImportAsync(...)).
3. The database now contains some basic data, several songs, etc.

Let me know if that's what you're looking for.

**Comment by JudahGabriel** [comment]
Alternately, if you're just looking for code to create the basic data, we can do that too. Let me know.

**Comment by kdcllc** [comment]
@JudahGabriel, I was able to programmaticly to import the data into the Docker container for Chavah.

```
if (host.IsDevelopment() && !string.IsNullOrEmpty(settings.FileName))
            {
                var importFilePath = Path.Combine(host.ContentRootPath, settings.FileName);

                var operation = new GetDatabaseNamesOperation(0, 1000); // 1000 is safe enough for me.
                var databaseNames = docStore.Maintenance.Server.Send(operation);
                if (databaseNames.Any(_ => _ == docStore.Database)) return services; // database already exists!

                docStore.Maintenance.Server.Send(
                new CreateDatabaseOperation(new DatabaseRecord(settings.DatabaseName)));

                var importOperation = docStore
                                        .Smuggler
                                        .ImportAsync(
                                            new DatabaseSmugglerImportOptions
                                            {
                                                OperateOnTypes = DatabaseItemType.Documents
                                            },
                                            importFilePath,
                                            new CancellationToken()).ConfigureAwait(false).GetAwaiter().GetResult();


                importOperation.WaitForCompletionAsync().Wait();
            }
```

**Comment by JudahGabriel** [comment]
As of this morning, we're now deployed live with .NET Core 2.1.
