### ISSUE TITLE
Security Pwned verification

### ISSUE THREAD

**Issue by kdcllc** [JudahGabriel/Chavah#70]
Include password verification thru https://haveibeenpwned.com/ with this library https://github.com/FaithLV/SharpPwned.NET into account registration and login flow.

**Comment by JudahGabriel** [comment]
Great minds think alike. Last week I was thinking, "We need a .NET API over the HIBP service. We could integrate that into Chavah."

Cool it already exists. It'd be great to implement this.

**Comment by JudahGabriel** [comment]
This is now merged in and deployed.
