### ISSUE TITLE
Migrate from Bower to LibMan (LibraryManager)

### ISSUE THREAD

**Issue by kdcllc** [JudahGabriel/Chavah#79]
Bower is being deprecated and Microsoft introduced LibMan library for [VS.NET 15.8.0 (Extension Included)](https://github.com/aspnet/LibraryManager/wiki/Using-LibMan-in-Visual-Studio) and [VSCode(CLI)](https://github.com/aspnet/LibraryManager/wiki/Using-LibMan-CLI).

For Angular6+ we won't have to use this and everything can be done via webpack and angular cli.

**Comment by JudahGabriel** [comment]
This fix is now merged into master.
