### ISSUE TITLE
Storing Application Secrets in Azure Vault

### ISSUE THREAD

**Issue by kdcllc** [JudahGabriel/Chavah#96]
This application utilizes many different secrets and also SSL certificate. For streamlining the development and deployment to move away from file-based application settings.

Utilize the following libraries:
-  Bet.AspNetCore
- Bet.AspNetCore.HealthChecks
- Bet.AspNetCore.Logging
- Bet.Extensions
- Bet.Extensions.AzureVault
- Bet.Extensions.Logging
[https://github.com/kdcllc/Bet.AspNetCore](https://github.com/kdcllc/Bet.AspNetCore)

**Comment by JudahGabriel** [comment]
This is implemented.
